### ISSUE TITLE
Blocks are replaced by other blocks

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/DimensionPortals#14]
There is an error in some part of the code that makes that when you put blocks, they generate other blocks and replace the old one.
What I have done was to test the plugins, first without the DimensionPortals (NetherPortals) and when I put the blocks, I put them well.
But when I activated NetherPortals and went to the Nether world, when I placed a block, more blocks started to appear around it, see the video for more info.
https://streamable.com/3wgj3i

And this is in the End world:
https://streamable.com/4kcii5

**Comment by Muqsit** [comment]
PocketMine [doesn't support](https://github.com/pmmp/PocketMine-MP/issues/4778) dimensions at the moment which is what causes this bug. You can install [DimensionFix](https://github.com/Muqsit/DimensionFix) to solve this issue.

**Comment by MrBlasyMSK** [comment]
> PocketMine [doesn't support](https://github.com/pmmp/PocketMine-MP/issues/4778) dimensions at the moment which is what causes this bug. You can install [DimensionFix](https://github.com/Muqsit/DimensionFix) to solve this issue.

Still happen whit [DimensionFix](https://github.com/Muqsit/DimensionFix)

**Comment by Muqsit** [comment]
Can you send a recording of this happening with DimensionFix installed?

**Comment by MrBlasyMSK** [comment]
> Can you send a recording of this happening with DimensionFix installed?

https://streamable.com/nmgly1

**Comment by Muqsit** [comment]
> > Can you send a recording of this happening with DimensionFix installed?
> 
> https://streamable.com/nmgly1

What's your nether world's folder called?

**Comment by MrBlasyMSK** [comment]
> > > Can you send a recording of this happening with DimensionFix installed?
> > 
> > 
> > https://streamable.com/nmgly1
> 
> What's your nether world's folder called?

```yml
# DimensionPortals v0.0.1

overworld:
  # Folder name of the world to use for overworld
  world: Factions

nether:
  # Folder name of the world to use for nether
  world: Nether
  # A list of other nether dimension worlds. These worlds will exhibit
  # properties of nether dimension, but won't be used for portal teleportation.
  sub-worlds: []
  # The number of ticks the player must wait in portal
  # before they get teleported to the nether.
  teleportation-duration: 80
  portal:
    # Frame block surrounding the portal
    frame-block: OBSIDIAN
    # Portal dimensions cap
    max-width: 30
    max-height: 30

end:
  # Folder name of the world to use for end
  world: End
  # A list of other end dimension worlds. These worlds will exhibit
  # properties of end dimension, but won't be used for portal teleportation.
  sub-worlds: []
  # The number of ticks the player must wait in portal
  # before they get teleported to the end.
  teleportation-duration: 0
  ```
